CREATE TABLE IF NOT EXISTS pending (
  uid TEXT PRIMARY KEY,
  gold INTEGER NOT NULL DEFAULT 0,
  epics INTEGER NOT NULL DEFAULT 0,
  heals INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);
